name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Android Lint (opcjonalnie)
        run: ./gradlew lint
        continue-on-error: true
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
      - name: Upload unit test reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: app/build/reports/tests/testDebugUnitTest
